import type { Server } from "@/types";

export const initialServers: Server[] = [
  {
    id: 1,
    name: "Server 1",
    currentLoad: 20,
    maxLoad: 100,
    baseResponseTime: 4.2,
    responseTime: 4.2,
    bandwidthMbps: 400,
    status: "available",
    activeRequests: 0,
    completedRequests: 0,
  },
  {
    id: 2,
    name: "Server 2",
    currentLoad: 35,
    maxLoad: 100,
    baseResponseTime: 5.1,
    responseTime: 5.1,
    bandwidthMbps: 600,
    status: "available",
    activeRequests: 0,
    completedRequests: 0,
  },
  {
    id: 3,
    name: "Server 3",
    currentLoad: 15,
    maxLoad: 100,
    baseResponseTime: 3.7,
    responseTime: 3.7,
    bandwidthMbps: 800,
    status: "available",
    activeRequests: 0,
    completedRequests: 0,
  },
  {
    id: 4,
    name: "Server 4",
    currentLoad: 50,
    maxLoad: 100,
    baseResponseTime: 6.4,
    responseTime: 6.4,
    bandwidthMbps: 500,
    status: "available",
    activeRequests: 0,
    completedRequests: 0,
  },
  {
    id: 5,
    name: "Server 5",
    currentLoad: 25,
    maxLoad: 100,
    baseResponseTime: 4.8,
    responseTime: 4.8,
    bandwidthMbps: 700,
    status: "available",
    activeRequests: 0,
    completedRequests: 0,
  },
];